name: Go Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.4" # Set Go version to use

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build for multiple platforms
      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o bb-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -o bb-darwin-amd64 .
          GOOS=windows GOARCH=amd64 go build -o bb-windows-amd64.exe .

      # Create a release and upload assets
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bb-linux-amd64
            bb-darwin-amd64
            bb-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.BBPR_GITHUB_TOKEN }}
